#!/bin/bash
  
red=$(printf "\033[31m")
green=$(printf "\033[32m") 
normal=$(printf "\033[m")
 
LIBNAME="libAmmServerlib.a"

if [ -e $LIBNAME ]
then
  rm $LIBNAME
fi   

# -O3 -fexpensive-optimizations
CFLAGS="-s"

gcc -c $CFLAGS main.c -o main.o 

PARTS_OF_LIB="main.o"

ar  rcs $LIBNAME $PARTS_OF_LIB

rm $PARTS_OF_LIB

if [ -e $LIBNAME ]
then
  echo "$green Success building Null $LIBNAME .. $normal"
else
  echo "$red Failure building Null $LIBNAME .. $normal"
fi



exit 0
