#!/bin/bash
 
echo "Compiling libAmmServerlib.a / Author : Ammar Qammaz"  
LIBNAME="libAmmServerlib.a"

if [ -e $LIBNAME ]
then
  rm $LIBNAME
fi   

CFLAGS="-s -O3 -fexpensive-optimizations"

gcc -c $CFLAGS main.c -o main.o
gcc -c $CFLAGS network.c -o network.o 
gcc -c $CFLAGS httprules.c -o httprules.o 
gcc -c $CFLAGS httpprotocol.c -o httpprotocol.o 
gcc -c $CFLAGS file_caching.c -o file_caching.o 
gcc -c $CFLAGS configuration.c -o configuration.o 
gcc -c $CFLAGS content_resources.c -o content_resources.o 

PARTS_OF_LIB="main.o network.o httprules.o httpprotocol.o file_caching.o configuration.o content_resources.o"

ar  rcs $LIBNAME $PARTS_OF_LIB

rm $PARTS_OF_LIB

if [ -e $LIBNAME ]
then
  echo "Success.."
else
  echo "Failure.."
fi



exit 0