#!/bin/bash

red=$(printf "\033[31m")
green=$(printf "\033[32m") 
normal=$(printf "\033[m")
OUTPUT="myurl"

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi 

CFLAGS="-s -Os -fexpensive-optimizations" 
OURLIBRARIES="../AmmServerlib/libAmmServerlib.a" 
LIBRARIES="-pthread -lrt -lz"

gcc  main.c -L. $OURLIBRARIES $LIBRARIES -o $OUTPUT


if [ -e $OUTPUT ]
then
  strip $OUTPUT
  echo "$green Success building $OUTPUT .. $normal"
else
  echo "$red Failure building $OUTPUT .. $normal"
fi

exit 0
