#!/bin/bash

red=$(printf "\033[31m")
green=$(printf "\033[32m") 
normal=$(printf "\033[m")

USE_DYNAMIC_LINKING=""
USE_SYSTEM_DYNAMIC_LIBRARY=""
OUTPUT="myurl"

for arg in $@; do 
 if [ "$arg" = "dynamic" ]
  then
   USE_DYNAMIC_LINKING="1"
  fi  
 if [ "$arg" = "system" ]
  then
   USE_SYSTEM_DYNAMIC_LIBRARY="1"
  fi  
done

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi 

CFLAGS="-s -Os -fexpensive-optimizations"  
LIBRARIES="-pthread -lm -lrt -ljpeg"

USELZ=`cat ../AmmServerlib/server_configuration.h | grep "#define ENABLE_COMPRESSION 1"`
if [ -n "$USELZ" ]
then 
 echo "$green Also Linking Lz $normal"
 LIBRARIES="$LIBRARIES -lz"
fi 

#Make a link to the main AmmarServer Lib , or maybe we could link to a system wide
#libAmmServerlib.so
if [ -n "$USE_SYSTEM_DYNAMIC_LIBRARY" ]
then 
 OURLIBRARIES="/usr/lib/ammarserver/libAmmServerlib.so" 
else
if [ -n "$USE_DYNAMIC_LINKING" ]
then 
 if [ ! -e libAmmServerlib.so ]
  then
   ln -s ../AmmServerlib/libAmmServerlib.so
 fi
 OURLIBRARIES="libAmmServerlib.so"  
else
 OURLIBRARIES="../AmmServerlib/libAmmServerlib.a"  
fi
fi
# -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -

OURLIBRARIES="$OURLIBRARIES ../AmmCaptcha/libAmmCaptcha.a"  

gcc  main.c -L. $OURLIBRARIES $LIBRARIES -o $OUTPUT


if [ -e $OUTPUT ]
then
  strip $OUTPUT
  echo "$green Success building $OUTPUT .. $normal"
else
  echo "$red Failure building $OUTPUT .. $normal"
fi

exit 0
