#!/bin/bash
killall memcheck-amd64-
valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes  --track-origins=yes src/ammarserver 2> AmmarServerDebug.log&
exit 0