#!/bin/bash

STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

# Start AmmarServer

until false; do
    src/Services/MyTube/mytube -port 8080 $@ 
    echo "Server 'mytube' stopped with exit code $?.  Respawning.." >&2
done
 
#src/Services/MyTube/mytube $@

cd "$STARTDIR"

exit 0
