#!/bin/bash

STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

# Start AmmarServer

until false; do
    src/Services/GeoPosShare/geoposshare -p 8082 $@ 
    echo "Server 'geoposshare' stopped with exit code $?.  Respawning.." >&2
done
  
cd "$STARTDIR"

exit 0 
