#!/bin/bash

STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

# Start AmmarServer

until src/Services/MyTube/mytube $@; do
    echo "Server 'mytube' crashed with exit code $?.  Respawning.." >&2
    sleep 1
done
 
#src/Services/MyTube/mytube $@

cd "$STARTDIR"

exit 0
