#ifndef APPLICATIONFILES_H_INCLUDED
#define APPLICATIONFILES_H_INCLUDED


enum { 
 APPLICATIONFILES_EMPTY=0,
 APPLICATIONFILES_EXE,
 APPLICATIONFILES_SWF,
 APPLICATIONFILES_PDF,
 APPLICATIONFILES_END_OF_ITEMS
};



int scanFor_applicationFiles(char * str,unsigned int strLength); 

#endif
