#ifndef FIRSTLINES_H_INCLUDED
#define FIRSTLINES_H_INCLUDED


enum { 
 FIRSTLINES_EMPTY=0,
 FIRSTLINES_GET,
 FIRSTLINES_HEAD,
 FIRSTLINES_POST,
 FIRSTLINES_PUT,
 FIRSTLINES_DELETE,
 FIRSTLINES_TRACE,
 FIRSTLINES_OPTIONS,
 FIRSTLINES_CONNECT,
 FIRSTLINES_PATCH,
 FIRSTLINES_END_OF_ITEMS
};



int scanFor_firstLines(char * str,unsigned int strLength); 

#endif
