#ifndef HTTPHEADER_H_INCLUDED
#define HTTPHEADER_H_INCLUDED


enum { 
 HTTPHEADER_EMPTY=0,
 HTTPHEADER_AUTHORIZATION,
 HTTPHEADER_ACCEPT_ENCODING,
 HTTPHEADER_COOKIE,
 HTTPHEADER_CONNECTION,
 HTTPHEADER_HOST,
 HTTPHEADER_IF_NONE_MATCH,
 HTTPHEADER_IF_MODIFIED_SINCE,
 HTTPHEADER_RANGE,
 HTTPHEADER_REFERRER,
 HTTPHEADER_REFERER,
 HTTPHEADER_USER_AGENT,
 HTTPHEADER_END_OF_ITEMS
};



int scanFor_httpHeader(char * str,unsigned int strLength); 

#endif
