#ifndef POSTHEADER_H_INCLUDED
#define POSTHEADER_H_INCLUDED


enum { 
 POSTHEADER_EMPTY=0,
 POSTHEADER_CONTENT_TYPE,
 POSTHEADER_CONTENT_DISPOSITION,
 POSTHEADER_CONTENT_LENGTH,
 POSTHEADER_END_OF_ITEMS
};



int scanFor_postHeader(char * str,unsigned int strLength); 

#endif
