#ifndef VIDEOFILES_H_INCLUDED
#define VIDEOFILES_H_INCLUDED


enum { 
 VIDEOFILES_EMPTY=0,
 VIDEOFILES_AVI,
 VIDEOFILES_MPEG4,
 VIDEOFILES_MPEG,
 VIDEOFILES_MP4,
 VIDEOFILES_WEBM,
 VIDEOFILES_MKV,
 VIDEOFILES_3GP,
 VIDEOFILES_H263,
 VIDEOFILES_H264,
 VIDEOFILES_FLV,
 VIDEOFILES_END_OF_ITEMS
};



int scanFor_videoFiles(char * str,unsigned int strLength); 

#endif
