#!/bin/bash 
echo "Compiling files.."  
gcc -c InputParser_C.c -o InputParser_C.o 

echo "Linking files.." 
ar  rcs libInputParser_C.a InputParser_C.o

echo "Cleaning compiled object files.."
rm InputParser_C.o 

echo "Done.."
exit 0
