#!/bin/bash
clear
killall memcheck-amd64-
valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes  --track-origins=yes  src/Services/Social/socialD 2> SocialDebug.log&


#valgrind  --tool=callgrind  src/Services/Social/socialD 2> SocialDebug.log&
exit 0
