#!/bin/bash

STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
 
until false; do
    cd src/Services/HabChan 
    ./habchan -p 8083 $@ 
    echo "Server 'habchan' stopped with exit code $?.  Respawning.." >&2
done

cd "$STARTDIR"

exit 0
