#!/bin/bash

STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
 
 src/Services/UserAccountsTester/useraccountstester -p 8080 $@  
  
cd "$STARTDIR"

exit 0
