#!/bin/bash

STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

# Start AmmarServer
src/Services/CinemaPilot/cinemapilot $@


cd "$STARTDIR"

exit 0
