#!/bin/bash

STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
cd ..

# Start AmmarServer
src/Services/MyBlog/myblog -p 8086 $@


cd "$STARTDIR"

exit 0
