#!/bin/bash
# I clear the terminal to make easier debugging between different starts of the program
clear



PROJECTNAMERELEASE="Social/social"
PROJECTNAMEDEBUG="Social/socialD"


STARTDIR=`pwd`
#Switch to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"


if [ -e src/Services/$PROJECTNAMERELEASE ]
then
  echo "Running release mode"
  src/Services/$PROJECTNAMERELEASE -p 8087 $@
  cd "$STARTDIR"
  exit 0
fi


if [ -e src/Services/$PROJECTNAMEDEBUG ]
then
  echo "Running release mode"
  src/Services/$PROJECTNAMEDEBUG -p 8087 $@
  cd "$STARTDIR"
  exit 0
fi



cd "$STARTDIR"

exit 0
