#!/bin/bash

OUTPUT="ammarserver"

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi 

CFLAGS="-s -Os -fexpensive-optimizations" 
OURLIBRARIES="AmmServerlib/libAmmServerlib.a" 
LIBRARIES="-pthread -lrt -lz"

gcc  main.c -L. $OURLIBRARIES $LIBRARIES -o $OUTPUT

if [ -e $OUTPUT ]
then
  echo "Success.."
else
  echo "Failure.."
fi




OUTPUT="ammarserverNULL"

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi 

CFLAGS="-s -O3 -fexpensive-optimizations" 
OURLIBRARIES="AmmServerNULLlib/libAmmServerlib.a" 
LIBRARIES="-pthread -lrt -lz"

gcc  main.c -L. $OURLIBRARIES $LIBRARIES -o $OUTPUT

if [ -e $OUTPUT ]
then
  echo "Success , AmmServerNULLlib is up to date.."
  rm $OUTPUT
else
  echo "Failure , please update the AmmServerNULLlib to mirror the real AmmarServer API headers .."
fi

 


exit 0