#!/bin/bash

red=$(printf "\033[31m")
green=$(printf "\033[32m") 
normal=$(printf "\033[m")
OUTPUT="ammarserver"

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi 

CFLAGS="-s -Os -fexpensive-optimizations" 
OURLIBRARIES="AmmServerlib/libAmmServerlib.a" 
LIBRARIES="-pthread -lrt -lz"

gcc  main.c -L. $OURLIBRARIES $LIBRARIES -o $OUTPUT


if [ -e $OUTPUT ]
then
  strip $OUTPUT
  echo "$green Success building $OUTPUT .. $normal"
else
  echo "$red Failure building $OUTPUT .. $normal"
fi





OUTPUT="ammarserverNULL"

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi 

CFLAGS="-s -O3 -fexpensive-optimizations" 
OURLIBRARIES="AmmServerNULLlib/libAmmServerlib.a" 
LIBRARIES="-pthread -lrt -lz"

gcc  main.c -L. $OURLIBRARIES $LIBRARIES -o $OUTPUT

if [ -e $OUTPUT ]
then
  echo "$green Success , AmmServerNULLlib is up to date.. $normal"
  rm $OUTPUT
else
  echo "$red Failure , please update the AmmServerNULLlib to mirror the real AmmarServer API headers .. $normal"
fi

 


exit 0
