#!/bin/bash
clear
killall memcheck-amd64-
#valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes  --track-origins=yes  ./naonetwalk 2> naonetwalk.log&


valgrind  --tool=callgrind  ./naonetwalk 2> naonetwalk.log&
exit 0
